name: First Workflow
on: [push, workflow_dispatch]
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Output github context
        run: echo "${{ toJson(github) }}"
  
  lint-job: 
    uses: ./.github/workflows/linter.yml